(() => {
  const projects=[
    {id:'p02',anchor:'projet02',n:'Phase 1',title:'Collecte & état des lieux',type:'Diagnostic initial',context:'Projet pédagogique 2',icon:'search',rncp:'BC01 — Concevoir un plan de rénovation énergétique',meta:'Maison de 1970 · 137 m² · audit pédagogique',tags:['CAP Renov+','Visuary'],actions:['Préparer le rendez-vous et collecter les données','Analyser le bâti, les équipements, les plans et les consommations','Identifier les informations manquantes et les points de vigilance'],deliverables:['Formulaire de préparation','Pré-synthèse client','Plan d’habitation','Rapport d’état des lieux CAP Renov'],skills:['Analyse du bâtiment existant','Lecture de plans','Diagnostic énergétique'],proof:'https://drive.google.com/drive/folders/1_k6_hkc5bPpR1BDYOwfIxtaqzIj3Y3s2'},
    {id:'p03',anchor:'projet03',n:'Phase 2',title:'Scénarios technico-financiers',type:'Scénarios & aides',context:'Projet pédagogique 3',icon:'chart-no-axes-combined',rncp:'BC01 — Concevoir un plan de rénovation énergétique',meta:'Comparer plusieurs solutions de rénovation',tags:['Scénarios','Décision'],actions:['Construire une comparaison multicritère','Analyser les coûts, gains, aides et reste à charge','Hiérarchiser les scénarios selon les objectifs du client'],deliverables:['Matrice comparative','Tableau aides / reste à charge','Synthèse de recommandation'],skills:['Comparaison multicritère','Analyse économique','Aide à la décision']},
    {id:'p04',anchor:'projet04',n:'Phase 3',title:'Rapport d’audit & recommandations',type:'Synthèse globale',context:'Projet pédagogique 4',icon:'file-text',rncp:'BC01 — Concevoir un plan de rénovation énergétique',meta:'Relier l’état initial, les scénarios chiffrés et les recommandations',tags:['Audit','Conseil'],actions:['Consolider les données de l’état des lieux','Développer et chiffrer les scénarios','Formuler une trajectoire de rénovation cohérente'],deliverables:['Rapport d’audit énergétique','Scénarios de rénovation chiffrés','Synthèse client et recommandations'],skills:['Audit énergétique','Recueil des besoins','Conseil client']},
    {id:'p05',anchor:'projet05',n:'Phase 4',title:'Consultation & analyse des offres',type:'Sécurisation de la décision',context:'Projet pédagogique 5',icon:'file-invoice',rncp:'BC02 — Superviser un projet de rénovation énergétique',meta:'Comparer les devis et sécuriser le passage à l’action',tags:['Devis','RGE'],actions:['Lire les devis et leurs périmètres','Vérifier les qualifications et les points de vigilance','Comparer les offres avec les recommandations de l’audit'],deliverables:['Tableau comparatif des offres','Liste des risques','Recommandation argumentée'],skills:['Analyse de devis','Vérification RGE','Gestion des risques']},
    {id:'p06',anchor:'projet06',n:'Phase 5',title:'Veille réglementaire & aides',type:'Fiabilisation des hypothèses',context:'Projet pédagogique 6',icon:'book-open-check',rncp:'BC03 — Conseiller et assister en rénovation énergétique',meta:'Sécuriser l’audit avec des références à jour',tags:['Veille','Réglementation'],actions:['Identifier les sources institutionnelles fiables','Analyser les impacts sur les scénarios et les aides','Mettre à jour les points de vigilance'],deliverables:['Note de veille','Tableau de suivi','Synthèse opérationnelle'],skills:['Veille réglementaire','Analyse documentaire','Synthèse']},
    {id:'p07',anchor:'projet07',n:'Phase 6',title:'Préparation de la mise en œuvre',type:'Planification & coordination',context:'Projet pédagogique 7',icon:'calendar-check',rncp:'BC02 — Superviser un projet de rénovation énergétique',meta:'Transformer les recommandations en plan d’action',tags:['Planning','Coordination'],actions:['Identifier les étapes de préparation','Structurer les rôles et responsabilités','Anticiper les blocages avant travaux'],deliverables:['Planning de préparation','Check-list de lancement','Matrice de responsabilités'],skills:['Planification','Coordination','Gestion des risques']},
    {id:'p08',anchor:'projet08',n:'Phase 7',title:'Contrôle de conformité & réception',type:'Vérification des résultats',context:'Projet pédagogique 8',icon:'file-check-2',rncp:'BC02 — Superviser un projet de rénovation énergétique',meta:'Vérifier la cohérence entre les préconisations et les travaux réalisés',tags:['Conformité','Réception'],actions:['Définir les points de contrôle','Tracer les écarts et les réserves','Vérifier les justificatifs de clôture'],deliverables:['Plan de contrôle','Tableau des réserves','Check-list de réception'],skills:['Contrôle qualité','Traçabilité','Réception']},
    {id:'p09',anchor:'projet09',n:'Phase 8',title:'Communication & décision collective',type:'Copropriété',context:'Projet pédagogique 9',icon:'presentation',rncp:'BC03 — Conseiller et assister en rénovation énergétique',meta:'Rendre l’audit compréhensible et préparer la décision',tags:['Copropriété','Pédagogie'],actions:['Vulgariser les constats et les scénarios','Préparer les supports de présentation','Anticiper les questions des décideurs'],deliverables:['Support AG','Livret copropriétaires','FAQ et synthèse de décision'],skills:['Communication','Pédagogie','Aide à la décision']}
  ];
  const grid=document.getElementById('projects-grid');
  const modal=document.getElementById('project-modal');
  const modalHead=document.getElementById('project-modal-header-content');
  const modalBody=document.getElementById('project-modal-body');
  const closeButton=document.getElementById('project-modal-close');
  if(!grid||!modal||!modalHead||!modalBody||!closeButton)return;
  const regions=document.querySelectorAll('body > nav, body > .nav-mobile, body > main, body > footer, body > .skip-link');
  let lastFocused=null;
  const icon=name=>`<i data-lucide="${name}" aria-hidden="true"></i>`;
  const chips=items=>items.map(item=>`<span class="chip">${item}</span>`).join('');
  const list=items=>items.map(item=>`<li>${item}</li>`).join('');
  const setInert=value=>regions.forEach(region=>{region.inert=value});
  grid.innerHTML=projects.map(project=>`<button type="button" class="project-card" id="${project.anchor}" data-id="${project.id}" aria-haspopup="dialog" aria-controls="project-modal" aria-label="Afficher le détail de ${project.n} : ${project.title}"><span class="project-banner" aria-hidden="true"><span class="project-number">${icon(project.icon)}${project.n}</span>${icon('arrow-up-right')}</span><span class="project-body"><h3>${project.title}</h3><p class="project-type">${project.type}</p><span class="chip-row">${chips(project.tags)}</span></span><span class="project-card-footer"><span>Voir le détail</span>${icon('arrow-right')}</span></button>`).join('');
  const renderIcons=()=>window.lucide?.createIcons?.({attrs:{class:['lucide-icon'],'aria-hidden':'true','stroke-width':1.8}});
  function openProject(id,{updateHash=true}={}){
    const project=projects.find(item=>item.id===id||item.anchor===id); if(!project)return;
    lastFocused=document.activeElement;
    modalHead.innerHTML=`<span class="project-modal-kicker">${icon(project.icon)}${project.n} · ${project.type}</span><h2 class="project-modal-title" id="project-modal-title">${project.title}</h2><p class="project-modal-sub" id="project-modal-sub">${project.meta}</p>`;
    modalBody.innerHTML=`<div class="project-training-box"><div class="project-training-item"><span class="project-training-label">Compétence RNCP mobilisée</span><strong>${project.rncp}</strong></div><div class="project-training-item"><span class="project-training-label">Contexte</span><strong>${project.context} · audit énergétique global</strong></div></div><div class="project-detail-grid"><section class="project-detail-block"><h3>${icon('list-checks')}Actions menées</h3><ul>${list(project.actions)}</ul></section><section class="project-detail-block"><h3>${icon('folder-check')}Livrables de l’audit</h3><ul>${list(project.deliverables)}</ul></section><section class="project-detail-block"><h3>${icon('badge-check')}Compétences</h3><div class="chip-row">${chips(project.skills)}</div></section><section class="project-detail-block"><h3>${icon('target')}Contribution démontrée</h3><p class="text-soft">Cette phase illustre une capacité directement mobilisable en rénovation énergétique, dans le cadre d’un audit pédagogique unique.</p></section></div><div class="project-modal-note"><p><strong>Preuves :</strong> ${project.proof?'livrables actuellement consultables.':'livrable non publié après sélection et anonymisation.'}</p>${project.proof?`<a href="${project.proof}" class="btn btn-sage" target="_blank" rel="noopener">Voir les livrables ${icon('external-link')}</a>`:'<span class="status-badge">Livrable non publié</span>'}</div>`;
    modal.hidden=false; modal.classList.add('open'); document.body.classList.add('modal-open'); setInert(true); if(updateHash)history.replaceState(null,'',`#${project.anchor}`); closeButton.focus(); renderIcons();
  }
  function closeProject({clearHash=true}={}){modal.classList.remove('open');modal.hidden=true;document.body.classList.remove('modal-open');setInert(false);if(clearHash&&location.hash.startsWith('#projet'))history.replaceState(null,'',location.pathname+location.search);if(lastFocused instanceof HTMLElement)lastFocused.focus()}
  grid.addEventListener('click',event=>{const card=event.target.closest('.project-card');if(card)openProject(card.dataset.id)});
  closeButton.addEventListener('click',()=>closeProject()); modal.addEventListener('click',event=>{if(event.target===modal)closeProject()});
  document.addEventListener('keydown',event=>{if(modal.hidden)return;if(event.key==='Escape'){closeProject();return}if(event.key!=='Tab')return;const focusable=[...modal.querySelectorAll('button:not([disabled]),a[href],[tabindex]:not([tabindex="-1"])')];if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}});
  const initial=location.hash.replace('#','');if(projects.some(p=>p.anchor===initial))openProject(initial,{updateHash:false});
  window.addEventListener('hashchange',()=>{const anchor=location.hash.replace('#','');const match=projects.find(p=>p.anchor===anchor);if(match)openProject(match.id,{updateHash:false});else if(!modal.hidden)closeProject({clearHash:false})});
  renderIcons();
})();